name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            archive: tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive: zip
          - target: x86_64-apple-darwin
            os: macos-latest
            archive: tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            archive: tar.gz
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - name: Build and Upload
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          manifest-path: soundness-cli/Cargo.toml
          bin: soundness-cli
          target: ${{ matrix.target }}
          build-tool: cross
          tar: ${{ matrix.archive == 'tar.gz' && 'all' || 'none' }}
          zip: ${{ matrix.archive == 'zip' && 'all' || 'none' }}
          token: ${{ secrets.GITHUB_TOKEN }}
